from typing import Any, Protocol


class IProgressPublisher(Protocol):
    def publish(self, channel: str, data: dict[str, Any]) -> None: ...

    def save_state(self, key: str, data: dict[str, Any], ttl: int = 3600) -> None: ...


class IProgressSubscriber(Protocol):
    async def connect(self) -> None: ...

    async def subscribe(self, channel: str) -> None: ...

    async def listen(self) -> Any: ...

    async def unsubscribe(self, channel: str) -> None: ...

    async def close(self) -> None: ...
